# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oura < Formula
  desc "Agent-first CLI and MCP server for the Oura Ring API v2"
  homepage "https://github.com/ouracli/oura"
  version "0.4.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ouracli/oura/releases/download/v0.4.3/oura_0.4.3_darwin_amd64.tar.gz"
      sha256 "dd892b4c1aa138e838c8f9f4f81779ad34682e5085501f2f7b6e0d00e15d2377"

      define_method(:install) do
        bin.install "oura"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ouracli/oura/releases/download/v0.4.3/oura_0.4.3_darwin_arm64.tar.gz"
      sha256 "3c0e771274c52a50a248a9eba0246d81d4ceb3ce3d26b025d10dad6d600ad5d5"

      define_method(:install) do
        bin.install "oura"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ouracli/oura/releases/download/v0.4.3/oura_0.4.3_linux_amd64.tar.gz"
      sha256 "1faf7e92e0907b56f4faad967babbea846f3de6838c4439532f98d0234f8cce0"
      define_method(:install) do
        bin.install "oura"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ouracli/oura/releases/download/v0.4.3/oura_0.4.3_linux_arm64.tar.gz"
      sha256 "b0e2dc09125f2f4f806a3759606436b718c651302eadb08ab385fc3ff56f8665"
      define_method(:install) do
        bin.install "oura"
      end
    end
  end

  test do
    assert_equal version.to_s, JSON.parse(shell_output("#{bin}/oura version")).fetch("version")
  end
end
