# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oura < Formula
  desc "Agent-first CLI and MCP server for the Oura Ring API v2"
  homepage "https://github.com/ouracli/oura"
  version "0.4.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ouracli/oura/releases/download/v0.4.2/oura_0.4.2_darwin_amd64.tar.gz"
      sha256 "08f25f8b7b82caf6fd228044cd6cabe3b93c88786217f252a5f728d1b2bed90e"

      define_method(:install) do
        bin.install "oura"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ouracli/oura/releases/download/v0.4.2/oura_0.4.2_darwin_arm64.tar.gz"
      sha256 "c4b18b83b1fe5884ccb2bbf5e36f728e33665b57f14c93f514374bb505ac1d08"

      define_method(:install) do
        bin.install "oura"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ouracli/oura/releases/download/v0.4.2/oura_0.4.2_linux_amd64.tar.gz"
      sha256 "9f013bd757ff4c0b1078d590f1915d28918a6b321c7f3f490bb9971c52c284f7"
      define_method(:install) do
        bin.install "oura"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ouracli/oura/releases/download/v0.4.2/oura_0.4.2_linux_arm64.tar.gz"
      sha256 "7a3f9d9400fabba0f8e66cd012733299d7b1b07c4b2db8ca5e77244e270916fe"
      define_method(:install) do
        bin.install "oura"
      end
    end
  end

  test do
    assert_equal version.to_s, JSON.parse(shell_output("#{bin}/oura version")).fetch("version")
  end
end
