# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oura < Formula
  desc "Agent-first CLI and MCP server for the Oura Ring API v2"
  homepage "https://github.com/ouracli/oura"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ouracli/oura/releases/download/v0.4.0/oura_0.4.0_darwin_amd64.tar.gz"
      sha256 "04e1099725a54c0f99f9f82362b0773e5f7eafea5f75bb0aa55e0ef53ce2cc34"

      define_method(:install) do
        bin.install "oura"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ouracli/oura/releases/download/v0.4.0/oura_0.4.0_darwin_arm64.tar.gz"
      sha256 "d184203e58809a978761385100801cb6b4887f69b1178fba13c7b72d21555cc9"

      define_method(:install) do
        bin.install "oura"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ouracli/oura/releases/download/v0.4.0/oura_0.4.0_linux_amd64.tar.gz"
      sha256 "0cbb64bcd820d6a209d6fbc5ca683e559e6fe5c59b9c2b613a5cd58c01dbccdf"
      define_method(:install) do
        bin.install "oura"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ouracli/oura/releases/download/v0.4.0/oura_0.4.0_linux_arm64.tar.gz"
      sha256 "7ef248761e4d89ee2c563706584e22b222d01111dcbf9d4c9653926c4537f76e"
      define_method(:install) do
        bin.install "oura"
      end
    end
  end

  test do
    assert_match "oura", shell_output("#{bin}/oura version")
  end
end
